services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile

    image: ros2docker
    container_name: ros2container
    hostname: ROS2Alex
    tty: true

    # DO NOT use host networking on macOS
    # network_mode: host

    volumes:
      - ~/Projects_robotics/workspace:/home/rosuser/ros2_ws

      # XQuartz socket forwarding (macOS GUI)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      # XQuartz display forwarding
      - DISPLAY=host.docker.internal:0

      # Qt fix for containers
      - QT_X11_NO_MITSHM=1

    working_dir: /home/rosuser/ros2_ws

    command: ["/bin/bash"]